services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-web
    ports:
      - "8000:80" # Map port 8000 on your host to port 80 in the container
    volumes:
      - ./html:/var/www/html # Mount the local "html" folder to the web server root
    depends_on:
      - db # Ensure the database starts before the PHP container

  db:
    image: mysql:8.0
    container_name: php-mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql # Persist database data in a Docker volume

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: php-phpmyadmin
    restart: always
    ports:
      - "8080:80" # Access phpMyAdmin on localhost:8080
    environment:
      PMA_HOST: db # Connect phpMyAdmin to the MySQL container
      MYSQL_ROOT_PASSWORD: root

volumes:
  db_data: # Define a named volume for database persistence
